-- 아래 쿼리는 CLASS_REQUEST, STUDENT, CLASS 테이블의 구조를 나타냅니다. 해당 테이블을 수정할 필요는 없습니다.
DESC CLASS_REQUEST;
DESC STUDENT;
DESC CLASS;

-- 1. CLASS_REQUEST 테이블에 대해 JOIN절과 USING을 이용해 STUDENT테이블과 결합하여
-- 신청번호(REQUEST_ID)와 학생이름(STUDENT_NAME)을 조회하는 쿼리를 작성해보세요.
SELECT REQUEST_ID, STUDENT_NAME
FROM CLASS_REQUEST c
JOIN STUDENT s
ON c.STUDENT_ID = s.STUDENT_ID
;

-- 2. CLASS_REQUEST 테이블에 대해 JOIN절과 USING을 이용해 CLASS테이블과 결합하여
-- 신청번호(REQUEST_ID)와 과목이름(CLASS_NAME)을 조회하는 쿼리를 작성해보세요.
SELECT REQUEST_ID, CLASS_NAME
FROM CLASS_REQUEST c
JOIN CLASS d
USING (CLASS_ID)
;

-- 3. CLASS_REQUEST 테이블에 대해 JOIN절과 USING을 이용해 STUDENT테이블, CLASS테이블과 결합하여
-- 신청번호(REQUEST_ID)와 학생이름(STUDENT_NAME), 과목이름(CLASS_NAME)을 조회하는 쿼리를 작성해보세요.
SELECT REQUEST_ID, STUDENT_NAME, CLASS_NAME
FROM CLASS_REQUEST r
JOIN STUDENT s
ON r.STUDENT_ID = s.STUDENT_ID
    JOIN CLASS c
    USING (CLASS_ID);
