SELECT * FROM USER, CLASS
WHERE USER.CLASS_ID = CLASS.CLASS_ID(+);

-- OUTER JOIN(LEFT JOIN)
SELECT * FROM USER LEFT[OUTER] JOIN CLASS
WHERE USER.CLASS_ID = CLASS.CLASS_ID;

-- OUTER JOIN(RIGHT JOIN)
SELECT * FROM USER RIGHT[OUTER] JOIN CLASS
WHERE USER.CLASS_ID = CLASS.CLASS_ID;

-- OUTER JOIN(FULL)
SELECT * FROM CLASS FULL OUTER JOIN USER
ON USER.CLASS_ID = CLASS.CLASS_ID;